In [9]:
import numpy as np

In [16]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Embedding, Input
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [3]:
voc_size = 10000

In [4]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]

In [5]:
one_hot_repr

[[6683, 3093, 7160, 1450],
 [6683, 3093, 7160, 8866],
 [6683, 9125, 7160, 8221],
 [2598, 8059, 6215, 6588, 7389],
 [2598, 8059, 6215, 6588, 2272],
 [8097, 6683, 6257, 7160, 4737],
 [7928, 9571, 3164, 6588]]

In [14]:
## word Embedding Representation
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, maxlen=sent_length, padding='pre')
embedded_docs

array([[   0,    0,    0,    0, 6683, 3093, 7160, 1450],
       [   0,    0,    0,    0, 6683, 3093, 7160, 8866],
       [   0,    0,    0,    0, 6683, 9125, 7160, 8221],
       [   0,    0,    0, 2598, 8059, 6215, 6588, 7389],
       [   0,    0,    0, 2598, 8059, 6215, 6588, 2272],
       [   0,    0,    0, 8097, 6683, 6257, 7160, 4737],
       [   0,    0,    0,    0, 7928, 9571, 3164, 6588]])

In [13]:
embedded_docs = pad_sequences(one_hot_repr, maxlen=sent_length, padding='post')
embedded_docs

array([[6683, 3093, 7160, 1450,    0,    0,    0,    0],
       [6683, 3093, 7160, 8866,    0,    0,    0,    0],
       [6683, 9125, 7160, 8221,    0,    0,    0,    0],
       [2598, 8059, 6215, 6588, 7389,    0,    0,    0],
       [2598, 8059, 6215, 6588, 2272,    0,    0,    0],
       [8097, 6683, 6257, 7160, 4737,    0,    0,    0],
       [7928, 9571, 3164, 6588,    0,    0,    0,    0]])

In [15]:
## feature representation for each word
dim = 10

In [20]:
model = Sequential()
model.add(Input((sent_length,)))
model.add(Embedding(voc_size, dim))
model.compile('adam', 'mse')

In [27]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


array([[[ 4.83845510e-02,  3.63986827e-02,  2.00688839e-04,
         -4.17285934e-02,  1.59174204e-03, -2.64751799e-02,
          3.55667993e-03,  6.03073835e-03, -3.66569385e-02,
         -1.69714913e-02],
        [ 4.83845510e-02,  3.63986827e-02,  2.00688839e-04,
         -4.17285934e-02,  1.59174204e-03, -2.64751799e-02,
          3.55667993e-03,  6.03073835e-03, -3.66569385e-02,
         -1.69714913e-02],
        [ 4.83845510e-02,  3.63986827e-02,  2.00688839e-04,
         -4.17285934e-02,  1.59174204e-03, -2.64751799e-02,
          3.55667993e-03,  6.03073835e-03, -3.66569385e-02,
         -1.69714913e-02],
        [ 4.83845510e-02,  3.63986827e-02,  2.00688839e-04,
         -4.17285934e-02,  1.59174204e-03, -2.64751799e-02,
          3.55667993e-03,  6.03073835e-03, -3.66569385e-02,
         -1.69714913e-02],
        [-1.25755295e-02, -4.97404002e-02, -3.42231281e-02,
         -3.30376849e-02,  3.31617258e-02,  3.44756134e-02,
         -4.97996099e-02,  2.06662342e-03, -4.644821

In [30]:
embedded_docs[0]

array([   0,    0,    0,    0, 6683, 3093, 7160, 1450])

In [33]:
model.predict(embedded_docs[0].reshape(1, sent_length))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step


array([[[ 0.04838455,  0.03639868,  0.00020069, -0.04172859,
          0.00159174, -0.02647518,  0.00355668,  0.00603074,
         -0.03665694, -0.01697149],
        [ 0.04838455,  0.03639868,  0.00020069, -0.04172859,
          0.00159174, -0.02647518,  0.00355668,  0.00603074,
         -0.03665694, -0.01697149],
        [ 0.04838455,  0.03639868,  0.00020069, -0.04172859,
          0.00159174, -0.02647518,  0.00355668,  0.00603074,
         -0.03665694, -0.01697149],
        [ 0.04838455,  0.03639868,  0.00020069, -0.04172859,
          0.00159174, -0.02647518,  0.00355668,  0.00603074,
         -0.03665694, -0.01697149],
        [-0.01257553, -0.0497404 , -0.03422313, -0.03303768,
          0.03316173,  0.03447561, -0.04979961,  0.00206662,
         -0.04644822,  0.0223528 ],
        [-0.00328662,  0.02153284,  0.03852607,  0.01282867,
         -0.0342828 ,  0.01613614,  0.04171054,  0.04150686,
          0.02784504,  0.00389705],
        [-0.01156697,  0.0181931 ,  0.03660414,  0.0